name: Update GitHub Stats

on:
  workflow_dispatch:   # 수동 실행 가능
  schedule:
    - cron: '0 0 * * *'  # 매일 업데이트

permissions:
  contents: write  # 저장소에 쓰기 권한 부여

jobs:
  generate_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats image
        run: |
          curl "https://github-readme-stats.vercel.app/api?username=suhyun751207&show_icons=true&theme=radical&count_private=true&include_all_commits=true" -o stats.svg

      - name: Commit and push stats.svg
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg
          git commit -m "Update GitHub Stats" || echo "No changes"
          git push

