name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'   # 매일 0시에 자동 실행
  workflow_dispatch:       # 수동 실행 가능

jobs:
  generate_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats image
        run: |
          curl "https://github-readme-stats.vercel.app/api?username=suhyun751207&show_icons=true&theme=radical&count_private=true&include_all_commits=true&token=${{ secrets.GH_STATS_TOKEN }}" -o stats.svg

      - name: Commit updated stats
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stats.svg
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
